--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/user/Wallpapers/fiolettapetapaski.png"

-- Special
background="#090610"
foreground="#c1c0c3"
cursor="#c1c0c3"

-- Colors
color0="#090610"
color1="#452957"
color2="#53316C"
color3="#55306E"
color4="#5D4671"
color5="#623B84"
color6="#6F4A91"
color7="#c1c0c3"
color8="#5c5669"
color9="#452957"
color10="#53316C"
color11="#55306E"
color12="#5D4671"
color13="#623B84"
color14="#6F4A91"
color15="#c1c0c3"
