# Shell variables
# Generated by 'wal'
wallpaper="/home/user/Wallpapers/fiolettapetapaski.png"

# Special
background='#090610'
foreground='#c1c0c3'
cursor='#c1c0c3'

# Colors
color0='#090610'
color1='#452957'
color2='#53316C'
color3='#55306E'
color4='#5D4671'
color5='#623B84'
color6='#6F4A91'
color7='#c1c0c3'
color8='#5c5669'
color9='#452957'
color10='#53316C'
color11='#55306E'
color12='#5D4671'
color13='#623B84'
color14='#6F4A91'
color15='#c1c0c3'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
